version: "3.6"

services:
  activator:
#    build:
#      context: .
#      args:
#        JAR_FILE: kgrid-activator-1.0.4-SNAPSHOT.jar
    environment:
      KGRID_CONFIG: "--cors.url=*  --management.info.git.mode=full"
    image: kgrid/activator
    ports:
      - "8080:8080"
    volumes:
      - ./shelf:/home/kgrid/shelf