# Java Maven CircleCI v0.0.Nofunction.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#

version: 2
jobs:

  ##############
  # Build job uses a go cli tool to create a github release
  ##############
  build:

    working_directory: ~/repo

    docker:
      - image: circleci/openjdk:11-jdk-node

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      #must run install to ensure multi module dependencies(simple-scripts-api) are cached
      - run: mvn -DskipTests clean install dependency:resolve-plugins dependency:go-offline -s .circleci/settings.xml

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - setup_remote_docker

      # run build and test
      - run:
         name: Build and Test And Verify
         command: |
            mvn verify -s .circleci/settings.xml
            mkdir -p ~/circle-artifacts/
            cp .*/target/kgrid-activator*.jar ~/circle-artifacts

      # save test results
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always

      - store_test_results:
          path: ~/junit


    # Will normally run deploy but if triggered with Release will prepare and perform maven release
    # run deploy to Heroku gets the mopen KOs and adds them to the shelf on Heroku
    # Release runs maven release and adds a Release to GitHub based on the tag via github api
      - run:
          name: Deploy/Release
          command: |

            if [ $RELEASE ]; then
                .circleci/release.sh
            else
                mkdir shelf
                HEROKU_API_KEY=$HEROKU_API_KEY mvn heroku:deploy -s .circleci/settings.xml
            fi

      - run:
          name: Deploy VuePress GitHub Pages
          command: |
            npm install && .circleci/vuepress_deploy.sh

      - store_artifacts:
          path: ~/circle-artifacts

      # Create a shelf with KOs
      - run:
          name: Create Heroku Shelf
          command: |
            .circleci/create_shelf.sh https://kgrid-activator.herokuapp.com/kos "opioid-collection cpic-collection example-collection cancer-risk-collection icon-array script-numerate postpci labwise ipp-collection"

workflows:
  version: 2
  main:
    jobs:
    - build:
        filters:
          branches:
            only: master
  earlymorning:
    triggers:
      - schedule:
          cron: "0 10 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build